# Generated by Django 5.2.13 on 2026-04-13 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スタンプ名称')),
                ('description', models.TextField(blank=True, verbose_name='説明文')),
                ('world', models.CharField(choices=[('world', 'オーバーワールド'), ('world_nether', 'ネザー'), ('world_the_end', 'ジ・エンド')], default='world', max_length=20, verbose_name='ワールド')),
                ('x', models.IntegerField(verbose_name='X座標')),
                ('y', models.IntegerField(verbose_name='Y座標')),
                ('z', models.IntegerField(verbose_name='Z座標')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='隠しスタンプ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
    ]
