# Generated by Django 5.2.13 on 2026-04-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='radius',
            field=models.IntegerField(default=10, verbose_name='半径'),
        ),
    ]
