# Generated by Django 5.2.13 on 2026-04-13 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_stamp_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='radius',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='半径'),
        ),
    ]
