# Generated by Django 5.2.13 on 2026-04-13 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_stamp_radius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True, verbose_name='Minecraft UUID')),
                ('last_known_name', models.CharField(max_length=50, verbose_name='最新のMCID')),
                ('points', models.IntegerField(default=0, verbose_name='所持ポイント')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StampLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pressed_at', models.DateTimeField(auto_now_add=True, verbose_name='初回取得日時')),
                ('last_pressed_at', models.DateTimeField(auto_now=True, verbose_name='最終取得日時')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.player')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.stamp')),
            ],
            options={
                'unique_together': {('player', 'stamp')},
            },
        ),
    ]
