# Generated by Django 5.2.13 on 2026-04-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_player_stamplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
    ]
