# Generated by Django 5.2.13 on 2026-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start_at', models.DateTimeField(blank=True, null=True, verbose_name='イベント開始日時')),
                ('event_end_at', models.DateTimeField(blank=True, null=True, verbose_name='イベント終了日時')),
                ('stamp_add_start_at', models.DateTimeField(blank=True, null=True, verbose_name='スタンプ追加開始日時')),
                ('stamp_add_end_at', models.DateTimeField(blank=True, null=True, verbose_name='スタンプ追加終了日時')),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定',
            },
        ),
    ]
