# Generated by Django 5.2.13 on 2026-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
