# Generated by Django 5.2.13 on 2026-04-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_userprofile_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
