# Generated by Django 5.2.13 on 2026-04-30 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_player_note_stamp_note_systemsetting_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamplog',
            name='last_pressed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終取得日時'),
        ),
    ]
