# Generated by Django 5.2.13 on 2026-04-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
