# Generated by Django 5.2.13 on 2026-04-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_call_staff',
            field=models.BooleanField(default=True, verbose_name='運営メンション可能か'),
        ),
    ]
