# Generated by Django 5.2.13 on 2026-04-30 09:44

from django.db import migrations
from django.contrib.auth.hashers import make_password
import os

def create_superuser(apps, schema_editor):
    CustomUser = apps.get_model('custom_auth', 'CustomUser')

    # ★ GitHubに直接書かず、Renderに設定した「環境変数」からこっそり受け取る
    username = os.environ.get('SUPERUSER_NAME')
    password = os.environ.get('SUPERUSER_PASS')
    email = 'admin@example.com'

    # もしRender側で環境変数が設定されていれば、作成を実行する
    if username and password:
        if not CustomUser.objects.filter(username=username).exists():
            CustomUser.objects.create(
                username=username,
                email=email,
                password=make_password(password),
                is_superuser=True,
                is_staff=True,
                is_active=True,
            )

class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_customuser_can_call_staff'),
    ]

    operations = [
    ]
