# Generated by Django 5.2.13 on 2026-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='タイトル')),
                ('type', models.CharField(choices=[('info', '情報'), ('firstlogin', '初回ログイン'), ('error', 'エラー'), ('warn', '警告')], default='info', max_length=20, verbose_name='タイプ')),
                ('message', models.CharField(max_length=300, verbose_name='メッセージ')),
                ('logtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
