# Generated by Django 5.2.13 on 2026-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllog',
            name='message',
            field=models.TextField(max_length=300, verbose_name='メッセージ'),
        ),
    ]
