# Generated by Django 5.2.13 on 2026-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_log', '0002_alter_alllog_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllog',
            name='type',
            field=models.CharField(choices=[('info', '情報'), ('dataadd', 'データ追加'), ('error', 'エラー'), ('warn', '警告')], default='info', max_length=20, verbose_name='タイプ'),
        ),
    ]
