# Generated by Django 5.2.13 on 2026-04-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_log', '0004_alter_alllog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllog',
            name='player',
            field=models.CharField(blank=True, max_length=20, verbose_name='プレイヤー'),
        ),
    ]
