# Generated by Django 5.2.13 on 2026-04-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_log', '0005_alllog_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllog',
            name='search_feed',
            field=models.TextField(blank=True, max_length=300, verbose_name='検索補助'),
        ),
    ]
