# Generated by Django 5.2.13 on 2026-04-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_log', '0006_alllog_search_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alllog',
            old_name='search_feed',
            new_name='search_assist',
        ),
    ]
