# Generated by Django 5.2.13 on 2026-04-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_log', '0007_rename_search_feed_alllog_search_assist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllog',
            name='message',
            field=models.TextField(verbose_name='メッセージ'),
        ),
    ]
